<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-12-07T05:11:18Z" name="Suite" finished-at="2021-12-07T05:11:44Z" duration-ms="25714">
    <groups>
    </groups>
    <test started-at="2021-12-07T05:11:18Z" name="Test" finished-at="2021-12-07T05:11:44Z" duration-ms="25714">
      <class name="TestCase.DSApplication">
        <test-method signature="itestlistener()[pri:0, instance:TestCase.DSApplication@2def7a7a]" started-at="2021-12-07T05:11:18Z" name="itestlistener" finished-at="2021-12-07T05:11:18Z" duration-ms="135" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Kurra] but found [Usha]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Kurra] but found [Usha]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at TestCase.DSApplication.itestlistener(DSApplication.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- itestlistener -->
        <test-method signature="DSAlgo()[pri:1, instance:TestCase.DSApplication@2def7a7a]" started-at="2021-12-07T05:11:19Z" name="DSAlgo" finished-at="2021-12-07T05:11:44Z" duration-ms="25293" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DSAlgo -->
      </class> <!-- TestCase.DSApplication -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
